name: CI

on:
  push:
    branches: [ main ]

env:
  GOPRIVATE: github.com/dukhyungkim
  REGISTRY: harbor.brique.kr
  IMAGE_NAME: chatbot/docgo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.17

      - name: Configure git for private modules
        env:
          GOPRIVATE_USERNAME: ${{ secrets.GOPRIVAE_USERNAME }}
          GOPRIVATE_TOKEN: ${{ secrets.GOPRIVAE_TOKEN }}
        run: git config --global url."https://${GOPRIVATE_USERNAME}:${GOPRIVATE_TOKEN}@github.com".insteadOf "https://github.com"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest

      - name: Run build
        run: go build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_REPO_USERNAME }}
        password: ${{ secrets.DOCKER_REPO_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
