name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.17

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest

      - name: Run build
        run: go build

      - name: Run ls
        run: ls

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_REPO_HOST }}/docgo:${{ github.run_number }}
        username: ${{ secrets.DOCKER_REPO_USERNAME }}
        password: ${{ secrets.DOCKER_REPO_TOKEN }}
        repository: ${{ secrets.DOCKER_REPO_HOST }}